# Generated by Django 4.1.2 on 2022-11-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_code'),
        ('api', '0002_auto_20201218_1626'),
    ]

    operations = [
    ]
